spring:
  application:
    name: product-catalog-api
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update # Hibernate creates/updates the schema automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true