spring:
  application:
    name: product-catalog-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:catalog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 2000 # 20 seconds
      idle-timeout: 300000 # 5 minutes

  jpa:
    hibernate:
      ddl-auto: update # Hibernate creates/updates the schema automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # also silence that warning from your logs

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
